name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank You for raising a issue, Hope you enjoy the journey of open source. if you want to connect with menter so please follow : \n LinkedIn :https://www.linkedin.com/in/durgeshkumar4993/ \n Github : https://github.com/Durgesh4993"
