name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello Contributer,\n Thank you for raising an issue, hope you enjoy the journey of open source \n Make sure you follow [CODE OF CONDUCT](https://github.com/Aman1-coder/GameSphere/blob/main/CODE_OF_CONDUCT.md) \n Don’t Forget to ⭐ our [GameSphere🎮](https://github.com/Aman1-coder/GameSphere)\n If you need any help/guide then contact with mentors \n [LinkedIn](https://www.linkedin.com/in/durgeshkumar4993/)\n [GitHub](https://github.com/Durgesh4993);"
